worker_processes auto;

events {
    worker_connections 1024;
}

http {
	server {
		include       /etc/nginx/mime.types;
		default_type  application/octet-stream;
		
		listen				443 ssl;
		server_name			souaguen.42.fr;
		gzip on;

		ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
		ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

		ssl_protocols			TLSv1.2 TLSv1.3;
		ssl_ciphers			HIGH:!aNULL:!MD5;
		ssl_prefer_server_ciphers	on;


		add_header	X-Frame-Options "SAMEORIGIN" always;
		add_header	X-Content-Type-Options "nosniff" always;
		add_header	X-XSS-Protection "1; mode=block" always;
		add_header	Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;		
	
		client_max_body_size	50M;
		
		location / {
			proxy_pass	http://frontend:3000/;
		}

		location /api/auth/ {
			proxy_pass http://auth:3001/;
		}
	}
}
